### ISSUE TITLE
anciens bordereaux

### ISSUE THREAD

**Issue by jframiara** [BenCarles31/PPE-G2#10]
Quand on demande l'affichage des anciens bordereaux, la page est vide. Même s'il n'y a pas de bordereau, il faut un message : "Pas de bordereau" par exemple, afin que l'on comprenne que la page est vide et que c'est normal.
![image](https://user-images.githubusercontent.com/23612833/50778071-62e74580-129d-11e9-8395-453fba42896c.png)

**Comment by BenCarles31** [comment]
Reglé
