### ISSUE TITLE
Bordereaux

### ISSUE THREAD

**Issue by jframiara** [BenCarles31/PPE-G2#12]
La distinction entre bordereau et anciens bordereaux n'est pas faite : on voit les mêmes bordereaux !

![image](https://user-images.githubusercontent.com/23612833/50778567-970f3600-129e-11e9-91ab-02301ae6e9f0.png)

![image](https://user-images.githubusercontent.com/23612833/50778583-9f677100-129e-11e9-9ff4-d26b980447ec.png)

Il faudrait les distinguer par l'année(en cours<>précédentes).

**Comment by BenCarles31** [comment]
la distinction a été clarifiée
