### ISSUE TITLE
Inscription et rendu sous FF

### ISSUE THREAD

**Issue by jframiara** [BenCarles31/PPE-G2#8]
Les tuiles de "Métro" ne réagissent pas correctement sur l'écran : la pop-up d'inscription n'apparait pas ou apparait hors du champs de l'écran (Firefox 64).
Par contre, sous Chrome 71, ça semble fonctionner correctement.
Si le site ne fonctionne que sur certains navigateurs, il faut le préciser dans la doc, idéalement dans le README.md.

**Comment by BenCarles31** [comment]
Readme.MD update
